name: Update GitHub User Info

on:
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * *"  # daily at 07:17 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate Markdown
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # optional, but recommended
        run: |
          python generate_github_user_info.py "${{ github.repository_owner }}" --out GITHUB_USER_INFO.md

      - name: Commit & Push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add GITHUB_USER_INFO.md
            git commit -m "chore: update GitHub user info [skip ci]"
            git push
          else
            echo "No changes."
          fi
